# Interactive documentation of the environment

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from Utils import test_env, utils

from importlib import reload

In [2]:
reload(test_env)

<module 'Utils.test_env' from '/m/home/home9/94/dainesn1/unix/Workdir/RelationalDeepRL/Utils/test_env.py'>

In [3]:
# Variable parameters
X = 5
Y = 5
initial = [2,0]
goal = [2,2]
MAX_STEPS = 10

game_params = dict(x=X, y=Y, initial=initial, goal=goal, max_steps=MAX_STEPS, 
                   greyscale_state=False, return_coord=True)

In [4]:
env = test_env.Sandbox(**game_params)

In [5]:
print(env)

Use greyscale state:  False
Use coordinate state:  True
Use one hot encoding state:  False
Boundary:  [5 5]
Initial position:  [2 0]
Current position:  [2 0]
Goal position:  [2, 2]
Optimal actions: 
	Right
Greyscale representation: 
 [[[3 3 3 3 3 3 3]
  [3 0 0 0 0 0 3]
  [3 0 0 0 0 0 3]
  [3 1 0 2 0 0 3]
  [3 0 0 0 0 0 3]
  [3 0 0 0 0 0 3]
  [3 3 3 3 3 3 3]]]



In [6]:
env.state = [0,2]
print(env)

Use greyscale state:  False
Use coordinate state:  True
Use one hot encoding state:  False
Boundary:  [5 5]
Initial position:  [2 0]
Current position:  [0, 2]
Goal position:  [2, 2]
Optimal actions: 
	Down
Greyscale representation: 
 [[[3 3 3 3 3 3 3]
  [3 0 0 1 0 0 3]
  [3 0 0 0 0 0 3]
  [3 0 0 2 0 0 3]
  [3 0 0 0 0 0 3]
  [3 0 0 0 0 0 3]
  [3 3 3 3 3 3 3]]]

